-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMJtSip6ZEAD5fjak
kRzVZdC6lLp2nsj2npQD0vRv2WCgCgYIKoZIzj0DAQehRANCAARdsSzPISFztsqt
V+h2w/N4LSbTWhHR9zNsSTTk/L85VY1kYiv3C3afaYoWXYMUYlksbW+5AcwysBWV
dBbUX77w
-----END PRIVATE KEY-----