// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUuAibH94XOy0WqO5GM3T3nxAvxDJdFvc',
    appId: '1:552259060335:web:67160f71f678a93e27839a',
    messagingSenderId: '552259060335',
    projectId: 'kezanat-alsama',
    authDomain: 'kezanat-alsama.firebaseapp.com',
    storageBucket: 'kezanat-alsama.appspot.com',
    measurementId: 'G-YDNRGWR44Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaKoJFbVwtlK-yUICbDdifZQCcxwbMBsY',
    appId: '1:552259060335:android:440414fc1a9746a927839a',
    messagingSenderId: '552259060335',
    projectId: 'kezanat-alsama',
    storageBucket: 'kezanat-alsama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuFX-LjtRsgUZs544WwWCRGQXH6dC60Og',
    appId: '1:552259060335:ios:0f0565db73b26d2c27839a',
    messagingSenderId: '552259060335',
    projectId: 'kezanat-alsama',
    storageBucket: 'kezanat-alsama.appspot.com',
    iosBundleId: 'com.dev.ramadan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuFX-LjtRsgUZs544WwWCRGQXH6dC60Og',
    appId: '1:552259060335:ios:f885db43d2dbd2f027839a',
    messagingSenderId: '552259060335',
    projectId: 'kezanat-alsama',
    storageBucket: 'kezanat-alsama.appspot.com',
    iosBundleId: 'com.example.ramadan',
  );
}
